"""export_weights.py — freeze a trained checkpoint into core/neural_policy_weights.h (N1, S0).

Canon: neural_policy_design.md §F.1 (the header layout — EXACTLY), CLAUDE_v2.md §9.8/§19.6/§20
(the versioned precompute artifact). The header is a DATA artifact: committed like a golden,
versioned by NP_VERSION, regenerated ONLY as a deliberate ADR event (§17). fp64 arrays, row-major,
%.17g formatting (round-trippable double text). The C forward pass (guidance_neural.c, §F.2) consumes
these arrays with a FIXED j-outer/i-inner loop order for bit-determinism.

LAYOUT PRODUCED (matches core/neural_policy_weights.h placeholder + neural_policy_design.md §F.1):
  NP_VERSION, NP_N_IN, NP_N_HID, NP_N_LAYERS, NP_N_OUT
  NP_IN_MU[NP_N_IN], NP_IN_SD[NP_N_IN]                 (frozen normalization)
  NP_OUT_SCALE[NP_N_OUT]                               (de-norm ranges: A_LAT_GAMUT,A_LAT_GAMUT,1.0)
  NP_W0[NP_N_HID][NP_N_IN],  NP_B0[NP_N_HID]
  NP_W1[NP_N_HID][NP_N_HID], NP_B1[NP_N_HID]
  NP_W2[NP_N_HID][NP_N_HID], NP_B2[NP_N_HID]
  NP_W_OUT[NP_N_OUT][NP_N_HID], NP_B_OUT[NP_N_OUT]
  (+ NP_ENG_THR_MIN for the throttle de-norm)

PyTorch Linear stores weight as [out, in], which is EXACTLY the row-major [j][i] the C loop reads
(acc += W[j][i]*x[i], j=out, i=in) — no transpose needed.

This exporter assumes NP_N_LAYERS==3 (the S0 topology, input->128->128->128->3). If a future rung
changes the depth, generalize the loop list below and bump NP_VERSION (a re-architecture event).

Usage: python export_weights.py --ckpt <ckpt.pt> --out ../core/neural_policy_weights.h [--np-version N]
"""

from __future__ import annotations
import argparse, hashlib, os, sys, datetime
import numpy as np


def fmt_vec(name, arr, ctype="double"):
    """Emit a 1-D C array initializer, %.17g, wrapped."""
    vals = ", ".join(f"{x:.17g}" for x in np.asarray(arr, dtype=np.float64).ravel())
    return f"static const {ctype} {name}[{arr.shape[0]}] = {{ {vals} }};\n"


def fmt_mat(name, mat, ctype="double"):
    """Emit a 2-D C array initializer [rows][cols], row-major, one row per line, %.17g."""
    mat = np.asarray(mat, dtype=np.float64)
    rows, cols = mat.shape
    lines = [f"static const {ctype} {name}[{rows}][{cols}] = {{"]
    for r in range(rows):
        vals = ", ".join(f"{x:.17g}" for x in mat[r])
        lines.append(f"  {{ {vals} }},")
    lines.append("};\n")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ckpt", required=True)
    ap.add_argument("--out", required=True, help="path to core/neural_policy_weights.h")
    ap.add_argument("--np-version", type=int, default=None,
                    help="override NP_VERSION (default: the checkpoint's np_version)")
    ap.add_argument("--action-tier", type=int, default=1, choices=(1, 2),
                    help="1 = Tier-A' lateral-only (hoverslam keeps throttle; every NP_VERSION "
                         "through 6). 2 = Tier-A full action (the net owns throttle too). The tier "
                         "is stamped into the header so it travels with the artifact that earned "
                         "it — guidance_neural.c compiles the throttle line in ONLY for tier 2.")
    args = ap.parse_args()

    import torch
    ck = torch.load(args.ckpt, map_location="cpu", weights_only=False)

    n_in, hid, layers, n_out = ck["n_in"], ck["hidden"], ck["layers"], ck["n_out"]
    if layers != 3:
        sys.exit(f"error: this exporter is specialized to NP_N_LAYERS==3 (got {layers}); "
                 f"generalize fmt list + bump NP_VERSION for a deeper net (a re-architecture event).")
    npv = args.np_version if args.np_version is not None else ck["np_version"]

    sd = ck["state_dict"]
    # Linear layers live at body.0, body.2, body.4, head (Tanh at odd indices carry no params).
    W0, B0 = sd["body.0.weight"], sd["body.0.bias"]
    W1, B1 = sd["body.2.weight"], sd["body.2.bias"]
    W2, B2 = sd["body.4.weight"], sd["body.4.bias"]
    Wo, Bo = sd["head.weight"], sd["head.bias"]

    # shape sanity (row-major [out, in])
    assert W0.shape == (hid, n_in), W0.shape
    assert W1.shape == (hid, hid), W1.shape
    assert W2.shape == (hid, hid), W2.shape
    assert Wo.shape == (n_out, hid), Wo.shape

    mu, sdv = ck["in_mu"], ck["in_sd"]
    out_scale = ck["out_scale"]
    eng_thr_min = float(ck.get("eng_thr_min", 0.40))
    val_mse = np.asarray(ck.get("val_mse", [float("nan")] * 3), dtype=np.float64)

    # dataset / provenance hash: hash the weights + normalization so the header is attributable.
    h = hashlib.sha256()
    for a in (W0, B0, W1, B1, W2, B2, Wo, Bo, mu, sdv, out_scale):
        h.update(np.asarray(a, dtype=np.float64).tobytes())
    weights_hash = h.hexdigest()[:16]
    date = datetime.date.today().isoformat()

    L = []
    L.append("/* neural_policy_weights.h — FROZEN policy theta (GM_NEURAL). GENERATED by")
    L.append(" * trainer/export_weights.py (offline PyTorch precompute). A VERSIONED CONSTANT, like the")
    L.append(" * aero tables or KDIV_SEEK — regenerating it is an ADR event (a new NP_VERSION + policy KAT")
    L.append(" * + full §13.6 re-golden). Canon: CLAUDE_v2.md §9.8/§19.6/§20; neural_policy_design.md §F.1.")
    L.append(" * fp64, row-major, %.17g. The C forward pass (guidance_neural.c) reads W[j][i] in a FIXED")
    L.append(" * j-outer/i-inner loop order for bit-determinism.")
    L.append(" *")
    L.append(f" * GENERATION STAMP: date={date}  NP_VERSION={npv}  weights_sha256[:16]={weights_hash}")
    L.append(f" *   val_mse[a_lat0,a_lat1,throttle] = [{val_mse[0]:.6e}, {val_mse[1]:.6e}, {val_mse[2]:.6e}]")
    L.append(f" *   dataset: n_rows={ck.get('n_rows','?')} n_runs={ck.get('n_runs','?')} ckpt={os.path.basename(args.ckpt)}")
    L.append(f" *   action tier: {args.action_tier} "
             f"({'Tier-A FULL ACTION — the net owns throttle' if args.action_tier >= 2 else 'Tier-A prime — lateral-only, hoverslam keeps throttle'})")
    L.append(" */")
    L.append("#ifndef BL_NEURAL_POLICY_WEIGHTS_H")
    L.append("#define BL_NEURAL_POLICY_WEIGHTS_H")
    L.append("")
    L.append(f"#define NP_VERSION   {npv}")
    L.append(f"#define NP_N_IN      {n_in}")
    L.append(f"#define NP_N_HID     {hid}")
    L.append(f"#define NP_N_LAYERS  {layers}")
    L.append(f"#define NP_N_OUT     {n_out}")
    L.append(f"#define NP_ENG_THR_MIN {eng_thr_min:.17g}   /* throttle de-norm floor (== core/constants.h ENG_THR_MIN) */")
    L.append(f"#define NP_ACTION_TIER {args.action_tier}   /* 1 = Tier-A' lateral-only; 2 = Tier-A, the net owns throttle */")
    L.append("")
    L.append("/* frozen input normalization (mu, sd) — computed from the TRAINING set, §C.3 */")
    L.append(fmt_vec("NP_IN_MU", mu))
    L.append(fmt_vec("NP_IN_SD", sdv))
    L.append("/* output de-norm ranges: a_lat channels -> +-A_LAT_GAMUT, throttle handled by NP_ENG_THR_MIN */")
    L.append(fmt_vec("NP_OUT_SCALE", out_scale))
    L.append("")
    L.append("/* layer 0: input -> hidden */")
    L.append(fmt_mat("NP_W0", W0))
    L.append(fmt_vec("NP_B0", B0))
    L.append("/* layer 1: hidden -> hidden */")
    L.append(fmt_mat("NP_W1", W1))
    L.append(fmt_vec("NP_B1", B1))
    L.append("/* layer 2: hidden -> hidden */")
    L.append(fmt_mat("NP_W2", W2))
    L.append(fmt_vec("NP_B2", B2))
    L.append("/* output head: hidden -> out (pre-tanh logits) */")
    L.append(fmt_mat("NP_W_OUT", Wo))
    L.append(fmt_vec("NP_B_OUT", Bo))
    L.append("")
    L.append("#endif /* BL_NEURAL_POLICY_WEIGHTS_H */")

    text = "\n".join(L) + "\n"
    with open(args.out, "w", newline="\n") as fh:
        fh.write(text)
    print(f"[export_weights] wrote {args.out}")
    print(f"[export_weights] NP_VERSION={npv} n_in={n_in} hid={hid} layers={layers} n_out={n_out} "
          f"weights_sha256[:16]={weights_hash}")


if __name__ == "__main__":
    main()
