// decode.ts — binary telemetry decoder (canon §10.3, Appendix B).
//
// MIRRORS core/protocol.h BlTlmFixed EXACTLY. Offsets below are the verified
// MSVC-compiled offsets (sizeof BlTlmFixed == 328, proto v4: +the wide socket
// TargetEstimate+EngineHealth after ignite_h; v3 added pred_impact[2]+ignite_h). In production this file is
// GENERATED by tools/gen_protocol_ts.py from protocol.h so the two sides cannot
// skew (canon §10.3, Appendix B). This hand-written version is the M3 reference
// and the shape the generator must emit; decode.test.ts golden-checks it against
// canonical bytes so a codegen change that drifts is caught.
//
// All fields little-endian. `littleEndian = true` is passed to every DataView read.

export const TLM_MAGIC = 0x304d4c54; // 'TLM0'
export const HELLO_MAGIC = 0x304c4c48; // 'HLL0'
export const EVT_MAGIC = 0x30545645; // 'EVT0'
export const STATS_MAGIC = 0x30545453; // 'STT0'

export const PROTO_VERSION = 4; // v4 (N0): the wide socket (TargetEstimate + EngineHealth)

export const TLM_FIXED_SIZE = 328; // v4: was 288 (+40 wide socket)
export const PLAN_KNOT_SIZE = 16;
export const CLOUD_SAMPLE_SIZE = 12;
export const PLAN_MAX = 64;
export const CLOUD_MAX = 128;

export const TLM_FLAG_SEA_ACTIVE = 1 << 0;
export const TLM_FLAG_RAW_MODE = 1 << 1;
export const TLM_FLAG_NAV_NOISY = 1 << 2;
export const TLM_FLAG_TARGET_MOVABLE = 1 << 3; // v4: target not pinned at origin
export const TLM_FLAG_ENGINE_OUT = 1 << 4; // v4: an engine has failed this run

// v4 target_src provenance (mirrors core/state.h TGT_* / protocol.h BL_TGT_SRC_*)
export enum TargetSrc {
  Fixed = 0, Seeded = 1, Beacon = 2, Perceived = 3, Drag = 4,
}

export enum Phase {
  Init = 0, Coast, EntryBurn, AeroDescent, LandingBurn, Touchdown, Settling,
  Landed, Tipped, Crashed, FuelDepleted, StructFail, ThermalFail, LOC,
}
export enum Verdict {
  None = 0, LandedPerfect, LandedGood, LandedHard, Tipped, Crashed,
}

/** One ghost-line knot. */
export interface PlanKnot {
  r: [number, number, number]; // sim-frame; convert at draw time
  throttle: number;
}
/** One possibility-cloud sample. */
export interface CloudSample {
  xy: [number, number];
  weight: number;
}

/** Fully decoded telemetry frame (still in SIM frame — conversion is at draw). */
export interface TlmFrame {
  step: number; // from u64; safe as double up to 2^53 steps (~ 5.7e11 s @125Hz)
  t: number; // sim seconds (f64)
  seq: number;
  flags: number;

  r: [number, number, number];
  v: [number, number, number];
  quat: [number, number, number, number]; // xyzw
  w: [number, number, number];

  mass: number;
  comZ: number;
  Idiag: [number, number, number];
  propLox: number;
  propRp1: number;

  throttleCmd: number;
  throttleAct: number;
  gimbalCmd: [number, number];
  gimbalAct: [number, number];
  finsAct: [number, number, number, number];

  rcsMask: number;
  nEng: number;
  phase: Phase;
  guidanceMode: number;
  verdict: Verdict;
  solverFlags: number;

  mach: number;
  qbar: number;
  alphaTotal: number;
  pAmb: number;
  pChamber: number;
  windLocal: [number, number, number];
  aBody: [number, number, number];
  qdotHeat: number;
  Qheat: number;

  tGo: number;
  distPad: number;
  predImpact: [number, number]; // v3: predicted impact point, world XY [m] (ballistic r+v*t_go)
  igniteH: number; // v3: landing-burn ignition altitude [m]

  // v4 THE WIDE SOCKET (§8.1): the TargetEstimate view + EngineHealth. Draw the estimate marker
  // (uncertainty ellipse from targetCov) distinct from the truth deck — "what the rocket believes".
  targetEstXy: [number, number]; // v4: estimated target position, world XY [m]
  targetEstVxy: [number, number]; // v4: estimated target velocity, world XY [m/s]
  targetCov: [number, number, number]; // v4: 2x2 covariance packed xx,yy,xy [m^2]
  targetSrc: TargetSrc; // v4: provenance (FIXED/SEEDED/BEACON/PERCEIVED/DRAG)
  targetValid: number; // v4: 0 before first acquisition
  targetAge: number; // v4: s since last target update (staleness)
  engHealth: number; // v4: per-engine health BITMASK (bit i = engine i healthy)
  engN: number; // v4: engines currently firing/available
  guidanceNpVer: number; // v4: neural-policy version (0 = none)

  deployFrac: number;
  stroke: [number, number, number, number];

  fAero: [number, number, number];

  deckZ: number;
  deckQuat: [number, number, number, number];

  plan: PlanKnot[];
  cloud: CloudSample[];
}

const LE = true;

/** Decode a TLM packet from an ArrayBuffer (the raw WebSocket binary frame). */
export function decodeTlm(buf: ArrayBuffer, byteOffset = 0): TlmFrame {
  const dv = new DataView(buf, byteOffset);

  const magic = dv.getUint32(0, LE);
  if (magic !== TLM_MAGIC) {
    throw new Error(`decodeTlm: bad magic 0x${magic.toString(16)} (expected TLM0)`);
  }
  const ver = dv.getUint16(4, LE);
  if (ver !== PROTO_VERSION) {
    throw new Error(`decodeTlm: protocol version ${ver} != ${PROTO_VERSION}`);
  }
  const flags = dv.getUint16(6, LE);

  // u64 step -> Number (loses precision only past 2^53; fine for step index).
  const step = Number(dv.getBigUint64(8, LE));
  const t = dv.getFloat64(16, LE);
  const seq = dv.getUint32(24, LE);
  // 28: _pad0

  const f = (off: number) => dv.getFloat32(off, LE);

  const r: [number, number, number] = [f(32), f(36), f(40)];
  const v: [number, number, number] = [f(44), f(48), f(52)];
  const quat: [number, number, number, number] = [f(56), f(60), f(64), f(68)];
  const w: [number, number, number] = [f(72), f(76), f(80)];

  const mass = f(84);
  const comZ = f(88);
  const Idiag: [number, number, number] = [f(92), f(96), f(100)];
  const propLox = f(104);
  const propRp1 = f(108);

  const throttleCmd = f(112);
  const throttleAct = f(116);
  const gimbalCmd: [number, number] = [f(120), f(124)];
  const gimbalAct: [number, number] = [f(128), f(132)];
  const finsAct: [number, number, number, number] = [f(136), f(140), f(144), f(148)];

  const rcsMask = dv.getUint16(152, LE);
  const nEng = dv.getUint8(154);
  const phase = dv.getUint8(155) as Phase;
  const guidanceMode = dv.getUint8(156);
  const verdict = dv.getUint8(157) as Verdict;
  const solverFlags = dv.getUint16(158, LE);

  const mach = f(160);
  const qbar = f(164);
  const alphaTotal = f(168);
  const pAmb = f(172);
  const pChamber = f(176);
  const windLocal: [number, number, number] = [f(180), f(184), f(188)];
  const aBody: [number, number, number] = [f(192), f(196), f(200)];
  const qdotHeat = f(204);
  const Qheat = f(208);

  const tGo = f(212);
  const distPad = f(216);
  const predImpact: [number, number] = [f(220), f(224)]; // v3
  const igniteH = f(228); // v3

  // v4 wide socket (@232)
  const targetEstXy: [number, number] = [f(232), f(236)];
  const targetEstVxy: [number, number] = [f(240), f(244)];
  const targetCov: [number, number, number] = [f(248), f(252), f(256)];
  const targetSrc = dv.getUint8(260) as TargetSrc;
  const targetValid = dv.getUint8(261);
  // 262: _pad1 (u16)
  const targetAge = f(264);
  const engHealth = dv.getUint8(268);
  const engN = dv.getUint8(269);
  const guidanceNpVer = dv.getUint16(270, LE);

  const deployFrac = f(272); // was 232
  const stroke: [number, number, number, number] = [f(276), f(280), f(284), f(288)];

  const fAero: [number, number, number] = [f(292), f(296), f(300)];

  const deckZ = f(304); // was 264
  const deckQuat: [number, number, number, number] = [f(308), f(312), f(316), f(320)];

  let planN = dv.getUint16(324, LE); // was 284
  let cloudN = dv.getUint16(326, LE);
  if (planN > PLAN_MAX) planN = PLAN_MAX; // defensive clamp (canon §10.3)
  if (cloudN > CLOUD_MAX) cloudN = CLOUD_MAX;

  // Tails follow the fixed head, tightly packed.
  const plan: PlanKnot[] = new Array(planN);
  let off = TLM_FIXED_SIZE;
  for (let i = 0; i < planN; i++) {
    plan[i] = {
      r: [f(off), f(off + 4), f(off + 8)],
      throttle: f(off + 12),
    };
    off += PLAN_KNOT_SIZE;
  }
  const cloud: CloudSample[] = new Array(cloudN);
  for (let i = 0; i < cloudN; i++) {
    cloud[i] = {
      xy: [f(off), f(off + 4)],
      weight: f(off + 8),
    };
    off += CLOUD_SAMPLE_SIZE;
  }

  return {
    step, t, seq, flags,
    r, v, quat, w,
    mass, comZ, Idiag, propLox, propRp1,
    throttleCmd, throttleAct, gimbalCmd, gimbalAct, finsAct,
    rcsMask, nEng, phase, guidanceMode, verdict, solverFlags,
    mach, qbar, alphaTotal, pAmb, pChamber, windLocal, aBody, qdotHeat, Qheat,
    tGo, distPad, predImpact, igniteH,
    targetEstXy, targetEstVxy, targetCov, targetSrc, targetValid, targetAge,
    engHealth, engN, guidanceNpVer,
    deployFrac, stroke,
    fAero,
    deckZ, deckQuat,
    plan, cloud,
  };
}

/** Total wire size of a TLM frame given its tail counts (for golden/round-trip). */
export function tlmFrameSize(planN: number, cloudN: number): number {
  return TLM_FIXED_SIZE + planN * PLAN_KNOT_SIZE + cloudN * CLOUD_SAMPLE_SIZE;
}

/** Peek the magic of any incoming frame to route it (TLM/EVT/STATS/HELLO). */
export function frameMagic(buf: ArrayBuffer, byteOffset = 0): number {
  return new DataView(buf, byteOffset).getUint32(0, LE);
}
